// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBuildJob = `-- name: CreateBuildJob :one
INSERT INTO build_jobs (project_id, created_by, max_retries)
VALUES ($1, $2, $3)
RETURNING id, project_id, status, retry_count, max_retries, failure_reason, cancel_requested, locked_by, started_at, finished_at, created_by, created_at, updated_at
`

type CreateBuildJobParams struct {
	ProjectID  uuid.UUID  `json:"project_id"`
	CreatedBy  *uuid.UUID `json:"created_by"`
	MaxRetries int32      `json:"max_retries"`
}

func (q *Queries) CreateBuildJob(ctx context.Context, arg CreateBuildJobParams) (BuildJob, error) {
	row := q.db.QueryRow(ctx, createBuildJob, arg.ProjectID, arg.CreatedBy, arg.MaxRetries)
	var i BuildJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.FailureReason,
		&i.CancelRequested,
		&i.LockedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildJobForOwner = `-- name: GetBuildJobForOwner :one
SELECT bj.id, bj.project_id, bj.status, bj.retry_count, bj.max_retries, bj.failure_reason, bj.cancel_requested, bj.locked_by, bj.started_at, bj.finished_at, bj.created_by, bj.created_at, bj.updated_at FROM build_jobs bj
JOIN projects p ON p.id = bj.project_id
WHERE bj.id = $1 AND p.owner_id = $2
`

type GetBuildJobForOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetBuildJobForOwner(ctx context.Context, arg GetBuildJobForOwnerParams) (BuildJob, error) {
	row := q.db.QueryRow(ctx, getBuildJobForOwner, arg.ID, arg.OwnerID)
	var i BuildJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.FailureReason,
		&i.CancelRequested,
		&i.LockedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildLogsForOwner = `-- name: GetBuildLogsForOwner :many
SELECT bl.id, bl.job_id, bl.stage, bl.level, bl.message, bl.created_at FROM build_logs bl
JOIN build_jobs bj ON bj.id = bl.job_id
JOIN projects p ON p.id = bj.project_id
WHERE bl.job_id = $1 AND p.owner_id = $2
ORDER BY bl.id ASC
`

type GetBuildLogsForOwnerParams struct {
	JobID   uuid.UUID `json:"job_id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetBuildLogsForOwner(ctx context.Context, arg GetBuildLogsForOwnerParams) ([]BuildLog, error) {
	rows, err := q.db.Query(ctx, getBuildLogsForOwner, arg.JobID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildLog{}
	for rows.Next() {
		var i BuildLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Stage,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildJobsForProject = `-- name: ListBuildJobsForProject :many
SELECT bj.id, bj.project_id, bj.status, bj.retry_count, bj.max_retries, bj.failure_reason, bj.cancel_requested, bj.locked_by, bj.started_at, bj.finished_at, bj.created_by, bj.created_at, bj.updated_at FROM build_jobs bj
JOIN projects p ON p.id = bj.project_id
WHERE bj.project_id = $1 AND p.owner_id = $2
ORDER BY bj.created_at DESC
`

type ListBuildJobsForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
}

func (q *Queries) ListBuildJobsForProject(ctx context.Context, arg ListBuildJobsForProjectParams) ([]BuildJob, error) {
	rows, err := q.db.Query(ctx, listBuildJobsForProject, arg.ProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildJob{}
	for rows.Next() {
		var i BuildJob
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.FailureReason,
			&i.CancelRequested,
			&i.LockedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestCancelForOwner = `-- name: RequestCancelForOwner :execrows
UPDATE build_jobs
SET cancel_requested = true, updated_at = now()
FROM projects p
WHERE build_jobs.project_id = p.id
  AND build_jobs.id = $1
  AND p.owner_id = $2
  AND build_jobs.status IN ('queued', 'building', 'scanning', 'deploying')
`

type RequestCancelForOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) RequestCancelForOwner(ctx context.Context, arg RequestCancelForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestCancelForOwner, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
