// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BuildJob struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Status          string             `json:"status"`
	RetryCount      int32              `json:"retry_count"`
	MaxRetries      int32              `json:"max_retries"`
	FailureReason   pgtype.Text        `json:"failure_reason"`
	CancelRequested bool               `json:"cancel_requested"`
	LockedBy        pgtype.Text        `json:"locked_by"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BuildLog struct {
	ID        int64              `json:"id"`
	JobID     uuid.UUID          `json:"job_id"`
	Stage     pgtype.Text        `json:"stage"`
	Level     string             `json:"level"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Name        string             `json:"name"`
	GitProvider string             `json:"git_provider"`
	RepoUrl     string             `json:"repo_url"`
	Branch      string             `json:"branch"`
	Runtime     string             `json:"runtime"`
	Environment string             `json:"environment"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	GithubID  int64              `json:"github_id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
