// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, name, git_provider, repo_url, branch, runtime, environment, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, name, git_provider, repo_url, branch, runtime, environment, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID     uuid.UUID  `json:"owner_id"`
	Name        string     `json:"name"`
	GitProvider string     `json:"git_provider"`
	RepoUrl     string     `json:"repo_url"`
	Branch      string     `json:"branch"`
	Runtime     string     `json:"runtime"`
	Environment string     `json:"environment"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.GitProvider,
		arg.RepoUrl,
		arg.Branch,
		arg.Runtime,
		arg.Environment,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.GitProvider,
		&i.RepoUrl,
		&i.Branch,
		&i.Runtime,
		&i.Environment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForOwner = `-- name: GetProjectForOwner :one
SELECT id, owner_id, name, git_provider, repo_url, branch, runtime, environment, created_by, created_at, updated_at FROM projects
WHERE id = $1 AND owner_id = $2
`

type GetProjectForOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForOwner, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.GitProvider,
		&i.RepoUrl,
		&i.Branch,
		&i.Runtime,
		&i.Environment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, name, git_provider, repo_url, branch, runtime, environment, created_by, created_at, updated_at FROM projects
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.GitProvider,
			&i.RepoUrl,
			&i.Branch,
			&i.Runtime,
			&i.Environment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
