// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error)
	GetUserByGithubID(ctx context.Context, githubID int64) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListProjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Project, error)
	UpsertUserByGithubID(ctx context.Context, arg UpsertUserByGithubIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
