// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, username, email, avatar_url, created_at, updated_at FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, username, email, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByGithubID = `-- name: UpsertUserByGithubID :one
INSERT INTO users (github_id, username, email, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_id) DO UPDATE
SET username   = EXCLUDED.username,
    email      = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING id, github_id, username, email, avatar_url, created_at, updated_at
`

type UpsertUserByGithubIDParams struct {
	GithubID  int64       `json:"github_id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUserByGithubID(ctx context.Context, arg UpsertUserByGithubIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByGithubID,
		arg.GithubID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
