// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendBuildLog = `-- name: AppendBuildLog :exec
INSERT INTO build_logs (job_id, stage, level, message) VALUES ($1, $2, $3, $4)
`

type AppendBuildLogParams struct {
	JobID   uuid.UUID   `json:"job_id"`
	Stage   pgtype.Text `json:"stage"`
	Level   string      `json:"level"`
	Message string      `json:"message"`
}

func (q *Queries) AppendBuildLog(ctx context.Context, arg AppendBuildLogParams) error {
	_, err := q.db.Exec(ctx, appendBuildLog,
		arg.JobID,
		arg.Stage,
		arg.Level,
		arg.Message,
	)
	return err
}

const claimNextBuildJob = `-- name: ClaimNextBuildJob :one
WITH next AS (
    SELECT id FROM build_jobs
    WHERE status = 'queued' AND cancel_requested = false
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE build_jobs bj
SET status = 'building', locked_by = $1, started_at = now(), updated_at = now()
FROM next
WHERE bj.id = next.id
RETURNING bj.id, bj.project_id, bj.status, bj.retry_count, bj.max_retries, bj.failure_reason, bj.cancel_requested, bj.locked_by, bj.started_at, bj.finished_at, bj.created_by, bj.created_at, bj.updated_at
`

// Atomically claim the oldest queued job. FOR UPDATE SKIP LOCKED lets multiple
// workers/replicas poll concurrently without ever grabbing the same row.
func (q *Queries) ClaimNextBuildJob(ctx context.Context, lockedBy pgtype.Text) (BuildJob, error) {
	row := q.db.QueryRow(ctx, claimNextBuildJob, lockedBy)
	var i BuildJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.FailureReason,
		&i.CancelRequested,
		&i.LockedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, name, git_provider, repo_url, branch, runtime, environment, created_by, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.GitProvider,
		&i.RepoUrl,
		&i.Branch,
		&i.Runtime,
		&i.Environment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCancelRequested = `-- name: IsCancelRequested :one
SELECT cancel_requested FROM build_jobs WHERE id = $1
`

func (q *Queries) IsCancelRequested(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isCancelRequested, id)
	var cancel_requested bool
	err := row.Scan(&cancel_requested)
	return cancel_requested, err
}

const markBuildJobCancelled = `-- name: MarkBuildJobCancelled :exec
UPDATE build_jobs SET status = 'cancelled', finished_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkBuildJobCancelled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBuildJobCancelled, id)
	return err
}

const markBuildJobFailed = `-- name: MarkBuildJobFailed :exec
UPDATE build_jobs SET status = 'failed', failure_reason = $2, finished_at = now(), updated_at = now() WHERE id = $1
`

type MarkBuildJobFailedParams struct {
	ID            uuid.UUID   `json:"id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) MarkBuildJobFailed(ctx context.Context, arg MarkBuildJobFailedParams) error {
	_, err := q.db.Exec(ctx, markBuildJobFailed, arg.ID, arg.FailureReason)
	return err
}

const markBuildJobSuccess = `-- name: MarkBuildJobSuccess :exec
UPDATE build_jobs SET status = 'success', finished_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkBuildJobSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBuildJobSuccess, id)
	return err
}

const requeueBuildJob = `-- name: RequeueBuildJob :exec
UPDATE build_jobs
SET status = 'queued', retry_count = retry_count + 1, locked_by = NULL, started_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RequeueBuildJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, requeueBuildJob, id)
	return err
}

const setBuildJobStatus = `-- name: SetBuildJobStatus :exec
UPDATE build_jobs SET status = $2, updated_at = now() WHERE id = $1
`

type SetBuildJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetBuildJobStatus(ctx context.Context, arg SetBuildJobStatusParams) error {
	_, err := q.db.Exec(ctx, setBuildJobStatus, arg.ID, arg.Status)
	return err
}
